config/routes.rb
Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    mount HudsonBase::Engine, :at  => 'hudson_base', :as => 'hudson_base'

    # Testing
    get ':site_id/iframe_test' => 'reservations#iframe_test'

    # Configuration (old URL format)
    get 'configuration', to: redirect { |params, request|
        site_id = request.query_parameters['network_site_id'] ||
            request.session[:site_id]

        request.protocol + request.host_with_port +
        request.fullpath.sub(/\/configuration.*/, '') + '/' +
            site_id + '/configuration' },
        as: 'configuration'

    # Res - first page
    get ':site_id', to: redirect { |params, request|
        request.protocol + request.host_with_port + request.fullpath + "/res/one_way" }, as: 'root'
    get ':site_id/res/one_way' => 'reservations#one_way', as: 'oneway'
    get ':site_id/res/round_trip' => 'reservations#round_trip', as: 'roundtrip'
    get ':site_id/res/multi_leg' => 'reservations#multi_leg', as: 'multi'
    get ':site_id/res/cruise_redirect' => 'reservations#cruise'
    post ':site_id/res/update_legs' => 'reservations#update_legs', as: 'update_legs'
    get ':site_id/res/initial_locations' => 'reservations#initial_locations',
        as: 'initial_locations'
    get ':site_id/res/locations' => 'reservations#locations', as: 'locations'
    get ':site_id/res/svc_extras' => 'reservations#svc_extras', as: 'svc_extras'
    get ':site_id/res/preload' => 'reservations#preload_data', as: 'preload'

    # Res - Cruise first page
    get ':site_id/res/cruise' => 'cruise_reservations#index', as: 'cruise'
    get ':site_id/res/cruise/arriving_locations' =>
          'cruise_reservations#arriving_locations',
        as: 'cruise_arriving_locations'
    get ':site_id/res/cruise/arriving_hot_dest' =>
          'cruise_reservations#arriving_hotel_destinations',
        as: 'cruise_arr_hotel_dests'
    get ':site_id/res/cruise/arriving_hot_hotels' =>
          'cruise_reservations#arriving_hotel_hotels',
        as: 'cruise_arr_hotel_hotels'
    get ':site_id/res/cruise/booking_container' =>
          'cruise_reservations#booking_container',
        as: 'cruise_booking_container'
    get ':site_id/res/cruise/departing_locations' =>
          'cruise_reservations#departing_locations',
        as: 'cruise_dep_locations'
    get ':site_id/res/cruise/departing_hot_dest' =>
          'cruise_reservations#departing_hotel_destinations',
        as: 'cruise_dep_hotel_dests'
    post ':site_id/res/cruise/update_legs' =>
          'cruise_reservations#update_legs',
        as: 'update_cruise_legs'

    # Res - services
    get ':site_id/services/flight_cities' => 'services#flight_cities',
            as: 'flight_cities'
    get ':site_id/services' => 'services#index', as: 'services'
    post ':site_id/services/update' => 'services#update', as: 'services_update'

    # Res - cart
    get ':site_id/cart' => 'cart#index', as: 'cart'
    get ':site_id/cart/new_trip' => 'cart#new_trip', as: 'new_trip'
    post ':site_id/cart/delete' => 'cart#delete', as: 'delete_trip'
    post ':site_id/cart/empty' => 'cart#empty', as: 'empty_cart'
    post ':site_id/cart/apply_coupon' => 'cart#apply_coupon', as: 'apply_coupon'
    post ':site_id/cart/remove_coupon' => 'cart#remove_coupon',
         as: 'remove_coupon'

    # Res - checkout
    get ':site_id/checkout' => 'cart#checkout', as: 'checkout'
    post ':site_id/checkout/validate' =>
        'cart#validate_checkout', as: 'validate_checkout'
    get ':site_id/checkout/book' => 'cart#book', as: 'book'
    get ':site_id/receipt' => 'cart#receipt', :as => :receipt

    # Attractions
    get ':site_id/attractions' => 'attractions#index'
    post ':site_id/attractions' => 'attractions#index'
    match ':site_id/attractions/widget' => 'attractions#widget',
          as: 'attractions_widget', via: :all
    get ':site_id/attractions/update_info' => 'attractions#update_info',
        as: 'attraction_update_info'
    post ':site_id/attractions/validate' => 'attractions#validate',
         as: 'attraction_validate'
    get ':site_id/attractions/widget_test' => 'attractions#test_iframe'
    get ':site_id/attractions' => 'attractions#index', as: 'attractions'
    get ':site_id/attractions/details' => 'attractions#details',
        as: 'attraction_details'

    # Profiles
    match ':site_id/group' => 'profile#group_login', as: :group, via: :all
    match ':site_id/profile/group_login_window' => 'profile#group_login_window',
            as: :group_login_window, via: :all
    match ':site_id/profile/login_window' => 'profile#login_window',
            as: :login_window, via: :all
    match ':site_id/profile/login_modal' => 'profile#login_modal',
            as: :login_modal, via: :all
    get ':site_id/join_preferred_rider' => 'profile#join', as: :join_preferred_rider
    get ':site_id/reload_profile' => 'profile#reload_profile', as: :reload_profile
    get ':site_id/preferred_rider_home' => 'profile#home', as: :preferred_rider_home
    get ':site_id/profile/pr_redirect' => 'profile#pr_redirect', as: :pr_redirect
    get ':site_id/logout' => 'profile#logout', as: :logout_profiles
    get ':site_id/logout_group' => 'profile#logout_group', as: :logout_group_profile

    # Misc.
    match ':site_id/join_mailing_list_window' => 'info#join_mailing_list_window',
            as: :join_mailing_list_window, via: :all
    match ':site_id/note' => 'contact_us#process_form', as: :notes, via: :all
    get ':site_id/error' => 'info#error', as: :error_page
    get ':site_id/block_check' => 'info#block_check', as: :block_check
    get ':site_id/cookies_test' => 'application#cookies_test', as: :cookies_test

    # Configuration
    get ':site_id/configuration' => 'configuration#index',
      as: 'config_home'
    match ':site_id/config/add_site' => 'configuration#add_site', as: 'add_site', via: :all
    match 'config/advanced' => 'configuration#advanced', via: :all
    match 'config/basic' => 'configuration#basic', via: :all
    get ':site_id/config/logout_user' => 'configuration#logout_user',
      as: 'config_logout'
    post 'config/update_site_details' => 'configuration#update_site_details', as: 'update_site_details'
    match ':site/:controller/:action', via: :all
    match 'config/delete_site' => 'configuration#delete_site', via: :all
    get 'config/activate_site' => 'configuration#activate_site'
    get 'config/disable_site' => 'configuration#disable_site'
    post 'config/add_airport' => 'configuration#add_airport', as: 'add_airport'
    post 'config/delete_airport' => 'configuration#delete_airport',
         as: 'delete_airport'

# Old below - can probably be deleted
    post 'profile/login' => 'profile#login'
    match ':site_id/login' => 'hudson_base/login#index', as: :login, via: :all
    match 'groups' => 'profile#groups', :as => :groups, via: :all

    match 'update_price' => 'attractions#update_price', as: :update_price, via: :all
    match 'logout' => 'configuration#logout', :as => :logout, via: :all
    match '/' => 'reservations#index', via: :all
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  # A warning message to the user alerting them that adding their items to
  # the cart means they can't edit them anymore.
  def add_to_cart_warning
    if add_to_cart_msg(no_span: true).present?
      content_tag :div, add_to_cart_msg, class: 'add-to-cart-warning'
    end
  end

  def additional_charges_label(site_id)
    label = dehtml(site_token(site_id, 'MA_SVCS_CAP_ADTLCHARGES'))
    label.blank? ? 'This time incurs additional charges:' : label
  end

  def address_label(res)
    site_token(res.home_site_id, 'ROADDRESSDESC', 'Address').dehtml
  end

  def address3_label(res)
    site_token(res.home_site_id, 'ADDRESSDESC3').dehtml
  end

  def adtl_gratuity_label(res)
    site_token(res.home_site_id, 'ADTLUSERGRATDESC', 'Additional Gratuity').dehtml
  end

  def airline_label(res)
    dehtml(site_token(res.home_site_id, 'AIRLINESDESC'))
  end

  def available_airlines(res)
    airlines = [' ']

    if current_trip.cruise?
      presenter = CruiseReservationsPresenter.new(current_session, self)
      airlines + presenter.available_airlines(res)
    else
      airlines + res.available_airlines.collect(&:name)
    end

  end

  def cruise_label(res)
    dehtml(site_token(res.home_site_id, 'MA_SVCS_CAP_SHIP', 'Ship name'))
  end

  def dropoff_time_label(site_id)
    dehtml(site_token(site_id, "MAX_SVCS_DO_TIME_PREFIX", 'Dropoff:'))
  end

	def fare_specific_message(res)
		message = res.location.try(:LocationStr)
    message.present? ? content_tag(:p, message).html_safe : ''
  end

  def flight_city_label(res)
    label = res.arrival? ?
      [raw_network_flight_city_a_label, raw_flight_city_a_label].find(&:present?) :
      [raw_network_flight_city_d_label, raw_flight_city_d_label].find(&:present?)
    label.html_safe
  end

  def flight_num_label(res)
    site_token(res.home_site_id, "#{res.Direction.upcase}FLIGHTNUMBERDESC").dehtml
  end

  def gratuity_enabled?(res)
    !gratuity_label(res).blank?
  end

  def gratuity_included_message(res)
    site_token(res.home_site_id, 'MA_SVCS_MSG_GRAT_INCLUDED',
        'A(n) %GRAT_PERCENT% gratuity of %GRAT_AMOUNT% is included in your fare.',
        noreplace: true)
  end

  def gratuity_label(res)
    dehtml(site_token(res.home_site_id, 'ALTUSERGRATDESC'))
  end

  def location_address(f, res)
    if res.location.readonly_address?
      res.location_addr
    else
      class_name = "form-control #{error_class(res, :location_addr)}"
      (field_error_label(res, :location_addr).to_s +
        f.text_area(res.location_addr_field,
            size: '25x3', class: class_name,
            placeholder: address_label(res))).html_safe
    end
  end

  def leg_header(leg)
    label = send("leg_header_#{current_trip.trip_type}_#{leg.Direction.downcase}")
    label = (current_trip.legs.index(leg)+1).ordinalize + ' ' + label if current_trip.trip_type == :multi
    content_tag :h3, label
  end

  def location_details(f, res)
    return nil unless address3_label(res).present?

    if res.location.readonly_address?
      res.location_details
    else
      f.text_field res.location_details_field, maxlength: 10,
          class: 'form-control loc-details',
          placeholder: address3_label(res)
    end
  end

  def location_header(res)
    res.arrival? ? location_header_a : location_header_d
  end

  def location_zip(f, res)
    if res.location.readonly_zip?
      res.location_zip
    else
      f.text_field res.location_zip_field, maxlength: 10,
          class: 'form-control loc-zip',
            placeholder: zip_label(res)
    end
  end

  def off_peak_label(site_id)
    dehtml(site_token(site_id, 'OFFSURCHARGECOLTEXT'))
  end

  def pickup_extras_header(site_id)
    site_token(site_id, 'PECOLTEXT', 'Extras').dehtml.html_safe
  end

  def pickup_extra_selected?(extras_list, this_extra, set_extra)
    # If this extra is the set extra, it's selected.
    if this_extra.type == set_extra
      return true

    # If the set_extra is not in the extras_list, select the first extra
    elsif !extras_list.find{|extra| extra.type == set_extra} && this_extra.type == extras_list[0].type
      return true

    else
      return false
    end
  end

  def pickup_time_label(site_id)
    site_token(site_id, "PUTIMECOLTEXT").html_safe
  end

  def pickup_time_message(site_id, direction)
    remove_crap_html!(site_token(site_id, "TIMESEL#{direction}")).html_safe
  end

  def pud_directions_label(res)
    dehtml(site_token(res.home_site_id, 'ADDRNOTESDESC'))
  end

  def service_description(service, res)
    remove_crap_html!(service.description.fix_image_urls(res.home_site_id)).html_safe
    #desc.gsub(/<br\/?>/i, '').html_safe
  end

  def service_fare(service)
    if service.fare_available?
      fare = number_to_currency(service.fare)
      parts = fare.split('.')

      html = ''
      if service.group_discount > 0.0
        original_fare = number_to_currency(service.fare.to_f + service.group_discount)
        html = "<span class='original-fare'>#{original_fare}</span>"
      end
      html += "<span class='fare-major'>#{parts[0]}</span><span class='fare-minor'>.#{parts[1]}</span>"
      html.html_safe
    else
      no_fare
    end
  end

  def service_group_discount_message(service)
    msg = service_group_discount_label(nil, noreplace: true).gsub(/%GROUPDISC%/, number_to_currency(service.group_discount))
    msg.gsub(/%GROUPALIAS%/, current_group_alias.to_s).html_safe
  end

  #TODO: Modify for multi-leg
  def services_header(leg)
    if current_trip.roundtrip?
      header = leg.departure? ? roundtrip_d_services_h1 : roundtrip_a_services_h1
    else
      header = oneway_services_h1
    end
    content_tag(:h1, header.html_safe).html_safe
  end

  def service_table_header(leg)
    header = site_token(leg.home_site_id, "SERVICESEL#{leg.Direction}")
    remove_crap_html!(header)
    content_tag(:p, header.html_safe)
  end

  def short_notice_label(site_id)
    dehtml(site_token(site_id, 'SNSURCHARGECOLTEXT'))
  end

  def show_airline?(res)
    airline_label(res).present? && flight_num_label(res).present?
  end

  def show_flight_city?(res)
    flight_city_label(res).present?
  end

  def show_flight_info?(res)
    res.capture_flight_info? &&
      !(airline_label(res).blank? && flight_num_label(res).blank? &&
        flight_city_label(res).blank? && res.departure?)
  end

  def show_flight_number?(res)
    !flight_num_label(res).blank? &&
          !Airports.airport_for(res.home_site_id, res.airport_key).cruise_terminal?
  end

  def show_pud_directions?(res)
    pud_directions_label(res).present?
  end

  def show_ship?(res)
    res.capture_ship?
  end

  def zip_label(res)
    dehtml(site_token(res.home_site_id, "PICKUPZIPDESC", 'Zip code'))
  end
end

app/views/services/_details.html.erb
<div class="details control-group">
  <%= notice_box %>

  <div class="details-summary">
    <div class="row list-group-item">
      <%= summary_pickup_label %>
      <span class="summary-times"></span>
    </div>
    <button type="button" class="btn btn-link pull-right show-details">
      <%= show_details_label %>
    </button>
  </div>

  <div class="row details-all">
    <div class="col-sm-6">
      <label><%= pickup_header %></label>
      <div class="hudson-subsection well">
        <%= pickup_time_message(leg.home_site_id, leg.Direction) %>
        <div class="pickup-times"> <!-- Pickup time selection -->
          <%= f.label :PickupTOD, pickup_time_label(leg.home_site_id) %>
          <div class="input-group" class="pickup-time">
            <%= f.select :PickupTOD, [], {},
                    class: 'pickup-tod form-control',
                    data: { selected: leg.PickupTOD,
                    time_format: time_format == :"12_hour" ? "h:mm a"  : "H:mm"}  %>
          </div>
        </div>

        <div class="pickup-extras"> <!-- Pickup extras -->
          <%= pickup_extras_header(leg.home_site_id) %>
          <div class="input-group">
            <%= f.select :PickupExtras,
                    [], {},
                    class: 'extras form-control'%>
          </div>
        </div>
      </div>

      <%= render partial: 'location', locals: {leg: leg, f: f} %>
    </div>

    <div class="col-sm-6" >
      <%= render partial: 'flight_info', locals: {leg: leg, f: f} %>
      <%= render partial: 'other', locals: {leg: leg, f: f} %>
    </div>
  </div>
</div>

app/views/services/_flight_info.html.erb
<% if show_flight_info?(leg) %>
  <label><%= flight_info_header %></label>
  <div class="flight-info hudson-subsection well">

    <% if show_airline?(leg) %>
      <%= f.label :Airline, airline_label(leg) %>
      <%= field_error_label(leg, :Airline) %>
      <div class="input-group <%= error_class(leg, :Airline) %>">
        <%= f.select :Airline, available_airlines(leg), {},
                class: 'airline form-control needsclick' %>
      </div>
    <% end %>

    <% if show_flight_number?(leg) %>
      <%= f.label :FlightNumber, flight_num_label(leg) %>
      <%= field_error_label(leg, :FlightNumber) %>
      <div class="input-group <%= error_class(leg, :FlightNumber) %>">
        <%= f.text_field :FlightNumber, class: 'form-control' %>
      </div>
    <% end %>

    <% if show_flight_city?(leg) %>
      <%= f.label :FlightCity, flight_city_label(leg) %>
      <%= field_error_label(leg, :FlightCity) %>
      <div class="input-group <%= error_class(leg, :FlightCity) %>">
        <%= f.text_field :FlightCity, value: f.object.FlightCity,
                class: 'form-control flight-city',
                autocapitalize: "off", autocorrect: "off", autocomplete: "off", spellcheck: 'false' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/services/_gratuity.html.erb
<% if gratuity_enabled?(leg) %>
  <div class="tip-field-container">
    <%= f.label :UserGratuity, adtl_gratuity_label(leg), class: 'gratuity-included' %>
    <%= f.label :UserGratuity, gratuity_label(leg), class: 'gratuity-not-included' %>

    <%= content_tag :div, ' ',
            class: 'gratuity-included gratuity-included-message',
            data: {message: gratuity_included_message(leg)} %>

    <%= field_error_label(leg, :UserGratuity) %>
    <%= content_tag :div,
            class: "input-group gratuity #{error_class(leg, :UserGratuity)}" do %>
      <%= f.text_field :UserGratuity,
              class: 'user-gratuity form-control', type: 'number',
              step: 'any' %>
    <% end %>

    <%= content_tag :a, tip_calculator_label,
            class: 'btn-link tip-calculator',
            data: {
              html: true,
              content: (render(partial: 'tip_calculator')).gsub(/"/, '&quot;').html_safe,
              placement: 'top'} %>

  </div>

<% end %>

app/views/services/_location.html.erb
<label><%= location_header(leg) %></label>
<div class="location hudson-subsection well">
  <p><%= leg.location_name %></p>
  <p><%= location_address(f, leg) %></p>
  <p><%= location_details(f, leg) %></p>
  <p><%= leg.location_city %>, <%= leg.location_state %> <%= location_zip(f, leg) %></p>
</div>

app/views/services/_other.html.erb
<% if show_pud_directions?(leg) ||
      gratuity_enabled?(leg) ||
      current_trip.cruise? %>
  <label><%= other_details_header %></label>
  <div class="other hudson-subsection well">

    <% if show_ship?(leg) %>
      <label><%= cruise_label(leg) %></label>
      <%= field_error_label(leg, :Ship) %>
      <div class="input-group <%= error_class(leg, :Ship) %>">
        <%= f.select :Ship, [' '] + leg.available_ships.collect(&:name), {},
                class: 'ship form-control needsclick' %>
      </div>
    <% end %>

    <% if show_pud_directions?(leg) %>
      <%= f.label :PUDDirections, pud_directions_label(leg) %>
      <div class="input-group">
        <%= f.text_area :PUDDirections, size: '25x3', class: 'form-control' %>
      </div>
    <% end %>


    <%= render partial: 'gratuity', locals: {leg: leg, f: f} %>
  </div>
<% end %>

app/views/services/_service.html.erb
<%= content_tag :li,
        class: "service-#{service.type} list-group-item #{'not-selectable' unless service.fare_available?}",
        data: {
          type: service.type, times: service.times,
          pickup_extras: service.pickup_extras,
          selectable: service.fare_available?,
          included_gratuity: {
            percentage: service.included_gratuity(true),
            amount: number_to_currency(service.included_gratuity),
            fare_without_gratuity: number_to_currency(service.fare_minus_gratuity) }
          } do %>
  <div class="service-description">
    <%= f.label :ServiceType, service_description(service, leg),
            value: service.type %>
  </div>


  <div class="service-fare"><%= service_fare(service) %></div>
  <div class="service-button">
    <% if service.fare_available? %>
      <button type="button" class="btn hudson-button"
          data-type="<%= service.type %>">
        <%= service_selection_label %>
      </button>
    <% end %>
  </div>
<% end %>

app/views/services/_services.html.erb
<div class="services-table"
    data-dropoff-prefix="<%= dropoff_time_label(leg.home_site_id) %>"
    data-offpeak-label="<%= off_peak_label(leg.home_site_id) %>"
    data-shortnotice-label="<%= short_notice_label(leg.home_site_id) %>"
    data-adtlcharges-label="<%= additional_charges_label(leg.home_site_id) %>"
    >
  <%= f.hidden_field :ServiceType,
          value: f.object.ServiceType,
          class: 'service-type' %>

  <div class="service-header-content">
    <%= service_table_header(leg) %>
    <%= fare_specific_message(leg) %>
  </div>

  <div class="list-group">
    <%= render partial: 'service', collection: services, locals: {leg: @leg, f: f} %>
  </div>
  <button type="button" class="btn btn-link pull-right show-all-services">
    <%= show_all_services_label %>
  </button>
</div>

app/views/services/_tip_calculator.html.erb
<label class="tip-label"><%= tip_calc_tip_label %></label>
<div class="form-group">
  <input type="text" name="tip_percent" class="form-control tip-percent">
  <span>%</span>
</div>

<p>
  <%= tip_calc_common_tips %>:<br/>
  <button class="btn btn-link common-tip" data-tip="20">20%</button>
  <button class="btn btn-link common-tip" data-tip="18">18%</button>
  <button class="btn btn-link common-tip" data-tip="15">15%</button>
</p>

<hr/>

<label><%= tip_calc_amount_label %></label>
$<span class="tip">0.00</span>

<i class="update-tip glyphicon glyphicon-remove"></i>

app/views/services/index.html.erb
<%= content_tag :div, class: 'leg-services-section', id: "leg#{@leg_index}",
        data: { index: @leg_index } do %>
  <%= render partial: 'shared/leg_summary',
          locals: {leg: @leg, index: @leg_index} %>

  <%= services_header(@leg) %>
  <%= form_for @leg, as: :leg, url: services_update_path,
          html: { role: 'form', id: "form-#{@leg_index}" } do |f| %>
    <input type="hidden" id="leg_index" name="leg_index" value="<%= @leg_index %>">

    <%= render partial: 'services', object: @leg.services,
            locals: {leg: @leg, f: f} %>

    <%= render partial: 'details', locals: {leg: @leg, f: f} %>

    <div class="button-container">
      <div class="buttons pull-right">
        <%= add_to_cart_warning if @leg == current_trip.legs.last %>

        <a href="<%= home_url %>"><%= back_link_caption %></a> <span class="divider">|</span>
        <%= content_tag :button, continue_btn_new_text, type: 'submit',
                data: {
                  'loading-text' => 'Saving...',
                  'edit-text' => continue_btn_edit_text,
                  'new-text' => continue_btn_new_text
                },
                class: "submit btn btn-hudson" %>
      </div>
    </div>
  <% end %>
<% end %>