config/routes.rb
Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    mount HudsonBase::Engine, :at  => 'hudson_base', :as => 'hudson_base'

    # Testing
    get ':site_id/iframe_test' => 'reservations#iframe_test'

    # Configuration (old URL format)
    get 'configuration', to: redirect { |params, request|
        site_id = request.query_parameters['network_site_id'] ||
            request.session[:site_id]

        request.protocol + request.host_with_port +
        request.fullpath.sub(/\/configuration.*/, '') + '/' +
            site_id + '/configuration' },
        as: 'configuration'

    # Res - first page
    get ':site_id', to: redirect { |params, request|
        request.protocol + request.host_with_port + request.fullpath + "/res/one_way" }, as: 'root'
    get ':site_id/res/one_way' => 'reservations#one_way', as: 'oneway'
    get ':site_id/res/round_trip' => 'reservations#round_trip', as: 'roundtrip'
    get ':site_id/res/multi_leg' => 'reservations#multi_leg', as: 'multi'
    get ':site_id/res/cruise_redirect' => 'reservations#cruise'
    post ':site_id/res/update_legs' => 'reservations#update_legs', as: 'update_legs'
    get ':site_id/res/initial_locations' => 'reservations#initial_locations',
        as: 'initial_locations'
    get ':site_id/res/locations' => 'reservations#locations', as: 'locations'
    get ':site_id/res/svc_extras' => 'reservations#svc_extras', as: 'svc_extras'
    get ':site_id/res/preload' => 'reservations#preload_data', as: 'preload'

    # Res - Cruise first page
    get ':site_id/res/cruise' => 'cruise_reservations#index', as: 'cruise'
    get ':site_id/res/cruise/arriving_locations' =>
          'cruise_reservations#arriving_locations',
        as: 'cruise_arriving_locations'
    get ':site_id/res/cruise/arriving_hot_dest' =>
          'cruise_reservations#arriving_hotel_destinations',
        as: 'cruise_arr_hotel_dests'
    get ':site_id/res/cruise/arriving_hot_hotels' =>
          'cruise_reservations#arriving_hotel_hotels',
        as: 'cruise_arr_hotel_hotels'
    get ':site_id/res/cruise/booking_container' =>
          'cruise_reservations#booking_container',
        as: 'cruise_booking_container'
    get ':site_id/res/cruise/departing_locations' =>
          'cruise_reservations#departing_locations',
        as: 'cruise_dep_locations'
    get ':site_id/res/cruise/departing_hot_dest' =>
          'cruise_reservations#departing_hotel_destinations',
        as: 'cruise_dep_hotel_dests'
    post ':site_id/res/cruise/update_legs' =>
          'cruise_reservations#update_legs',
        as: 'update_cruise_legs'

    # Res - services
    get ':site_id/services/flight_cities' => 'services#flight_cities',
            as: 'flight_cities'
    get ':site_id/services' => 'services#index', as: 'services'
    post ':site_id/services/update' => 'services#update', as: 'services_update'

    # Res - cart
    get ':site_id/cart' => 'cart#index', as: 'cart'
    get ':site_id/cart/new_trip' => 'cart#new_trip', as: 'new_trip'
    post ':site_id/cart/delete' => 'cart#delete', as: 'delete_trip'
    post ':site_id/cart/empty' => 'cart#empty', as: 'empty_cart'
    post ':site_id/cart/apply_coupon' => 'cart#apply_coupon', as: 'apply_coupon'
    post ':site_id/cart/remove_coupon' => 'cart#remove_coupon',
         as: 'remove_coupon'

    # Res - checkout
    get ':site_id/checkout' => 'cart#checkout', as: 'checkout'
    post ':site_id/checkout/validate' =>
        'cart#validate_checkout', as: 'validate_checkout'
    get ':site_id/checkout/book' => 'cart#book', as: 'book'
    get ':site_id/receipt' => 'cart#receipt', :as => :receipt

    # Attractions
    get ':site_id/attractions' => 'attractions#index'
    post ':site_id/attractions' => 'attractions#index'
    match ':site_id/attractions/widget' => 'attractions#widget',
          as: 'attractions_widget', via: :all
    get ':site_id/attractions/update_info' => 'attractions#update_info',
        as: 'attraction_update_info'
    post ':site_id/attractions/validate' => 'attractions#validate',
         as: 'attraction_validate'
    get ':site_id/attractions/widget_test' => 'attractions#test_iframe'
    get ':site_id/attractions' => 'attractions#index', as: 'attractions'
    get ':site_id/attractions/details' => 'attractions#details',
        as: 'attraction_details'

    # Profiles
    match ':site_id/group' => 'profile#group_login', as: :group, via: :all
    match ':site_id/profile/group_login_window' => 'profile#group_login_window',
            as: :group_login_window, via: :all
    match ':site_id/profile/login_window' => 'profile#login_window',
            as: :login_window, via: :all
    match ':site_id/profile/login_modal' => 'profile#login_modal',
            as: :login_modal, via: :all
    get ':site_id/join_preferred_rider' => 'profile#join', as: :join_preferred_rider
    get ':site_id/reload_profile' => 'profile#reload_profile', as: :reload_profile
    get ':site_id/preferred_rider_home' => 'profile#home', as: :preferred_rider_home
    get ':site_id/profile/pr_redirect' => 'profile#pr_redirect', as: :pr_redirect
    get ':site_id/logout' => 'profile#logout', as: :logout_profiles
    get ':site_id/logout_group' => 'profile#logout_group', as: :logout_group_profile

    # Misc.
    match ':site_id/join_mailing_list_window' => 'info#join_mailing_list_window',
            as: :join_mailing_list_window, via: :all
    match ':site_id/note' => 'contact_us#process_form', as: :notes, via: :all
    get ':site_id/error' => 'info#error', as: :error_page
    get ':site_id/block_check' => 'info#block_check', as: :block_check
    get ':site_id/cookies_test' => 'application#cookies_test', as: :cookies_test

    # Configuration
    get ':site_id/configuration' => 'configuration#index',
      as: 'config_home'
    match ':site_id/config/add_site' => 'configuration#add_site', as: 'add_site', via: :all
    match 'config/advanced' => 'configuration#advanced', via: :all
    match 'config/basic' => 'configuration#basic', via: :all
    get ':site_id/config/logout_user' => 'configuration#logout_user',
      as: 'config_logout'
    post 'config/update_site_details' => 'configuration#update_site_details', as: 'update_site_details'
    match ':site/:controller/:action', via: :all
    match 'config/delete_site' => 'configuration#delete_site', via: :all
    get 'config/activate_site' => 'configuration#activate_site'
    get 'config/disable_site' => 'configuration#disable_site'
    post 'config/add_airport' => 'configuration#add_airport', as: 'add_airport'
    post 'config/delete_airport' => 'configuration#delete_airport',
         as: 'delete_airport'

# Old below - can probably be deleted
    post 'profile/login' => 'profile#login'
    match ':site_id/login' => 'hudson_base/login#index', as: :login, via: :all
    match 'groups' => 'profile#groups', :as => :groups, via: :all

    match 'update_price' => 'attractions#update_price', as: :update_price, via: :all
    match 'logout' => 'configuration#logout', :as => :logout, via: :all
    match '/' => 'reservations#index', via: :all
  end
end

app/helpers/cart_helper.rb
module CartHelper

  def add_res_link
    # If we have attached config for the most recent item in the cart.
    if current_attached_config && current_attached_config.new_url.present?
      url = current_attached_config.new_url
      return link_to cart_add_res_label, '#',
                     class: 'add-res btn btn-link',
                     onclick: "window.top.location.href = '#{url}';"
    end

    # If the customer has defined a custom link, we want to update the parent.
    if cart_add_res_destination.present?
      return link_to cart_add_res_label, '#',
                     class: 'add-res btn btn-link',
                     onclick: "window.top.location.href = '#{cart_add_res_destination}';"
    end

    # Otherwise
    link_to cart_add_res_label, add_res_url,
            class: 'add-res btn btn-link'
  end

  def add_res_url
    # URL for booking a new trip of the most recently added type.
    if cart.items_ready_for_booking.length > 0
      trip_type = cart.items_ready_for_booking.last.trip_type
      return send("#{trip_type}_url")
    end

    root_url
  end

  def allow_coupon_removal?
    current_session.coupon_applied? &&
      current_session.coupon_type != :immutable_coupon
  end

  # Coupons are allowed if the coupon label is set and we don't have a profile
  # loaded that has disabled coupons.
  def allow_coupons?
    apply_coupon_label(no_span: true).present? &&
      (current_session.group_profile.blank? ||
        current_session.group_profile.coupon_type == :coupon)
  end

  def attractions
    cart.items_ready_for_booking.collect(&:available_attractions).flatten.uniq
  end

  def attractions_available?
    cart.items_ready_for_booking.any? &:attractions_available?
  end

  # Checks if any of a leg's FlightCity can be associated with
  # a valid network airport (so we can try to sell service to the customer
  # in that region)
  def can_book_travel_to_flight_city?(leg)
    airports = current_network.airports.collect &:Code

    if (airport = airport_from_flight_city(leg.FlightCity)) && airports.include?(airport)
      return true
    end

    false
  end

  def cart_flight_city_caption(leg)
    label = send("cart_flight_city_cap_#{leg.Direction.downcase}", {}, noreplace: true)
    label.gsub(/%FLIGHTCITY%/, leg.FlightCity).html_safe
  end

  def credit_card_message
    # Any of the cash payment types have a message?
    payment = collected_payment_types.find{|pt| pt.payment_type == 0}
    payment ?  content_tag(:p, payment.message.html_safe) : nil
  end

  # Some analytics will send duplicated data if the user reloads the receipt
  # page. This method helps ensure they are only displayed once.
  def display_receipt_analytics?(itinerary_id)
    @display_receipt_analytics ||= begin
      times_displayed = session[itinerary_id].to_i
      session[itinerary_id] = times_displayed + 1
      times_displayed == 0
    end
  end

  def email_sub_checked?(key)
    # An email subscription should be checked off by default or if the user
    # explicitly selected it. We need to catch the case where the user
    # unselected it and make sure we don't re-select it on them.
    flash[:mailing_list] == nil || flash[:mailing_list][key] == '1'
  end

  def exclusive_programs
    current_user_profile.enrolled_programs.find_all {|p| p.earning_type == :exclusive}
  end

  def mask_number(number)
    number.to_s.size < 5 ? number.to_s : (('*' * number.to_s[0..-5].length) + number.to_s[-4..-1])
  end

  def multiple_exclusive_programs?
    exclusive_programs.length > 1
  end

  def offer_multiple_payment_types?
    [offer_cc?, offer_cash?, offer_db?].find_all{|a|a}.length > 1
  end

  def payment_type(type, label, is_default = false)
    active = (current_session.payment_type == type ||
        (current_session.payment_type.blank? && is_default))
    content_tag :li, class: "#{'active' if active}" do
      content_tag :a, label, id: "pt-#{type}",
          class: "#{'hudson-button' if active}", data: {type: type}
    end.html_safe
  end

  def programs_earning_points
    programs = current_user_profile.enrolled_programs
        .find_all {|p| p.earning_type == :always}
        .collect{|p| content_tag :p, p.name}
        .join.html_safe
  end

  def receipt?
    controller_name == 'cart' && action_name == 'receipt'
  end

  def receipt_analytics(cart)
    content = Tokens.for(current_site_id, 'MA_RECEIPT_ANALYTICS',
        :noreplace => true, :no_imagefix => true)
    unless content.blank?
      content = content.gsub(/%TOTALFARE%/, number_with_precision(cart.total.to_s, precision: 2))
      content = content.gsub(/%(IID|ID)%/, cart.items[0].legs[0].ItineraryID.to_s)
      content = content.gsub(/%OP_BREAKDOWN%/, revenue_breakdown(cart))
    end
    content.html_safe
  end

  def resid_list(cart)
    resids = []
    cart.items.each do |trip|
      trip.legs.each {|leg| resids << leg.WResID }
    end
    resids.join(",")
  end

  def resid_list_for_email(cart, email, options = {})
    resids = []
    cart.items.each do |trip|
      trip.legs.each {|leg| resids << leg.WResID if leg.EmailAddr == email }
    end
    if options[:nice]
      return resids.join(", ")
    else
      return resids.join(",")
    end
  end

  def revenue_breakdown(cart)
    legs = cart.items.collect(&:legs).flatten.compact
    legs.collect {|leg| "#{leg.home_site_id}:#{number_with_precision(leg.Fare, precision: 2)}"}.join('|')
  end

  def cart_service_group_discount_message(leg, cart)
    msg = service_group_discount_label(nil, noreplace: true).gsub(/%GROUPDISC%/, number_to_currency(leg.GroupDisc))
    msg.gsub(/%GROUPALIAS%/, (cart.group_alias || '')).html_safe
  end

  def hide_attraction_attract?
    cart_hide_attractions_attract.to_i == 1
  end

  def show_book_another_link?
    hide_book_another_link.to_i != 1
  end

  def show_email_validation_field?
    current_session.email_validation?
  end

  def show_flight_city_marketing?(leg)
    show_provider_links? && can_book_travel_to_flight_city?(leg)
  end

  def show_points_info?
    current_user_profile &&
        !(current_user_profile.enrolled_programs.nil? ||
            current_user_profile.enrolled_programs.empty?)
  end

  def show_preferred_rider_button?
    show_preferred_rider_button.to_i == 1
  end

  # Show provider links if there is only one primary site represented in the cart.
  # If there are more than one site represented the customer may have already
  # added travel to/from their flight city.
  def show_provider_links?
    bookable_trips.collect(&:primary_sites).flatten.uniq.length == 1
  end

  def show_service_discount_row?(leg)
    leg.GroupDisc.to_f > 0.0
  end

  def show_time_in_cart?(trip)
    !trip.is_attraction? ||
      (trip.is_attraction? && trip.legs[0].attraction_display_time)
  end

  def trips_have_multiple_email_addresses?(trips)
    unique_email_addresses(trips).length > 1
  end

  # The number of rows a trip will generate in the cart table.
  def trip_table_row_count(trip)
    trip.legs.reduce(0) do |row_count, leg|
      row_count + 1 + [
        show_service_discount_row?(leg),
        show_flight_city_marketing?(leg) ].delete_if(&:!).size
    end
  end
end

app/views/cart/_analytics.html.erb
<% if display_receipt_analytics?(cart.items[0].legs[0].ItineraryID) %>

  <% content_for(:analytics) do -%>

    <% if universal_google_analytics? %>
      <script>
        ga('require', 'ecommerce');   // Load the ecommerce plug-in.

        ga('ecommerce:addTransaction', {
          'id': '<%= cart.items[0].legs[0].ItineraryID %>', // Transaction ID. Required
          'affiliation': '<%= j current_host %>', // Affiliation or store name
          'revenue': '<%= number_with_precision(cart.total, precision: 2) %>', // Grand Total
          'shipping': '', // Shipping
          'tax': '<%= number_with_precision(cart.total_tax, precision: 2) %>' // Tax
        });

        <% cart.items.each do |trip| -%>
          <% trip.legs.each do |leg| -%>
            ga('ecommerce:addItem', {
              'id': '<%= cart.items[0].legs[0].ItineraryID %>', // Transaction ID. Required
              'name': "<%= leg.home_site_id %>: <%= j leg.PickupLocation %> => " +
                "<%= j leg.DropOffLocation %>", // Product name. Required
              'sku': '<%= leg.WResID %>', // SKU/code
              'category': '<%= leg.ServiceType %>', // Category or variation
              'price': '<%= number_with_precision(leg.Fare, precision: 2) %>', // Unit price
              'quantity': '1' // Quantity
            });
          <% end -%>
        <% end -%>

        ga('ecommerce:send');      // Send transaction and item data to Google Analytics.
      </script>

    <% else %>
      <script type="text/javascript">
        _gaq.push(['_addTrans',
          '<%= cart.items[0].legs[0].ItineraryID %>', // Order ID
          '<%= j current_host %>', //Affiliation
          '<%= number_with_precision(cart.total, precision: 2) %>', // Total
          '<%= number_with_precision(cart.total_tax, precision: 2) %>', // Tax
          '', // Shipping
          '', // City
          '', // State
          '' // Country
          ]);

        <% cart.items.each do |trip| -%>
          <% trip.legs.each do |leg| -%>
            _gaq.push(['_addItem',
              '<%= cart.items[0].legs[0].ItineraryID %>', // Order ID
              '<%= leg.WResID %>', // SKU
              "<%= leg.home_site_id %>: <%= j leg.PickupLocation %> => " +
                "<%= j leg.DropOffLocation %>",
              '<%= leg.ServiceType %>', // Category
              '<%= number_with_precision(leg.Fare, precision: 2) %>', // Price
              '1' // Quantity
              ]);
          <% end -%>
        <% end -%>

        _gaq.push(['_trackTrans']);
      </script>
    <% end %>

    <%= receipt_analytics(cart) %>
  <% end -%>

<% end -%>

app/views/cart/_cart.html.erb
<% if cart.items_ready_for_booking.empty? %>
  <p class="cart-empty"><%= cart_no_items %></p>
<% else %>
  <div class=" cart-container">
    <%= render partial: 'trip',
            collection: cart.items_ready_for_booking,
            locals: {
              read_only: defined?(read_only) ? read_only : false,
              cart: cart
            } %>

    <table class="total pull-right">
      <%= render partial: 'coupon', locals: { cart: cart } %>

      <tr class="total-line">
        <td>
          <%= cart_total_label %>
          <span class="total-value"><%= number_to_currency(cart.total) %></span>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/cart/_contact_info.html.erb
<label><%= contact_header %></label>
<div class="hudson-subsection well" id="contact">
  <div class="row">
    <div class="col-sm-12">

    </div>

    <div class="col-sm-6">
      <label><%= strip_font_tags(name_label) %></label>
      <%= field_error_label(current_session, :Name) %>
      <div class="form-group input-with-icon contact-name
                <%= error_class(current_session, :Name) %>">
        <%= f.text_field :Name, class: 'form-control' %>
        <i class="fa fa-user pull-right"></i>
      </div>

      <label><%= strip_font_tags(email_label) %></label>
      <%= field_error_label(current_session, :EmailAddr) %>
      <div class="form-group input-with-icon contact-email
                <%= error_class(current_session, :EmailAddr) %>">
        <%= f.text_field :EmailAddr, type: 'email', class: 'form-control' %>
        <i class="fa fa-envelope pull-right"></i>
      </div>

      <% if show_email_validation_field? -%>
        <label><%= strip_font_tags(validate_email_label) %></label>
        <%= field_error_label(current_session, :EmailAddr_confirmation) %>
        <div class="form-group input-with-icon contact-validate-email
                    <%= error_class(current_session, :EmailAddr_confirmation) %>">
          <%= f.text_field :EmailAddr_confirmation, type: 'email', class: 'form-control' %>
          <i class="fa fa-envelope pull-right"></i>
        </div>
      <% end %>
    </div>

    <div class="col-sm-6">
      <% if current_session.telephone_displayed? %>
        <label><%= strip_font_tags(telephone_label) %></label>
        <%= field_error_label(current_session, :Telephone) %>
        <div class="form-group input-with-icon contact-phone
                    <%= error_class(current_session, :Telephone) %>">
          <%= f.text_field :Telephone, type: 'tel', class: 'form-control' %>
          <i class="fa fa-phone pull-right"></i>
        </div>
      <% end %>

      <% if current_session.alt_telephone_displayed? %>
        <label><%= strip_font_tags(telephone2_label) %></label>
        <%= field_error_label(current_session, :Telephone2) %>
        <div class="form-group input-with-icon contact-phone2
                  <%= error_class(current_session, :Telephone2) %>">
          <%= f.text_field :Telephone2, type: 'tel', class: 'form-control' %>
          <i class="fa fa-phone pull-right"></i>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cart/_coupon.html.erb
<% if cart.group_alias.present? || allow_coupons? %>
  <tr class="coupon-line"><td>
    <form class="apply-coupon-form">

      <!-- preloading -->
      <i class="fa fa-spinner fa-spin fa-large" style="opacity: 0"></i>

      <% if cart.group_alias.present? %>
        <em><%= cart.group_name %></em>
        <%= coupon_applied_suffix %>
        <% if !receipt? &&
              current_session.coupon_applied? &&
              allow_coupon_removal? %>
          (<button class="btn btn-link remove-coupon"
                  data-loading-text='<i class="fa fa-spinner fa-spin fa-large"></i> removing...'>
            <%= remove_coupon_label %>
          </button>)
        <% end %>

        <span class="total-discount">
          -<%= number_to_currency(cart.total_discount) %>
        </span>

      <% elsif !receipt? && allow_coupons? %>
        <div class="form-group form-inline">
          <label for="coupon">
            <%= apply_coupon_label(no_span: true) %>
          </label>

          <input type="text" name="coupon" class="form-control input-sm"
               id="coupon-code">
          <%= content_tag :button,
                          apply_coupon_button,
                          class: "btn btn-xs apply-coupon",
                          data: {
                            loading_text: '<i class="fa fa-spinner fa-spin fa-large"></i> Applying...'
                          } %>
      </div>

      <% end %>
    </form>

    <%= render partial: 'coupon_issue_modal' %>
  </td></tr>
<% end %>

app/views/cart/_coupon_issue_modal.html.erb
<div class='modal' id='coupon-issue-modal'>
  <div class='modal-dialog modal-lg'>
    <div class='modal-content'>
      <div class="issue-explanation">
        <p class="description"></p>
        <ul class="issues"></ul>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="action btn btn-primary"
                data-loading-text="Loading...">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/cart/_email_subs.html.erb
<% if @email_subs.present? %>
  <label><%= email_subs_header %></label>
  <div id="mailing-lists">
    <% @email_subs.each do |sub| -%>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="mailing_list[<%= sub.Key %>]"
            value="1"
            <%= 'checked' if email_sub_checked?(sub.Key) %>>
          <%= sub.Label %>
        </label>
      </div>
    <% end -%>
  </div>
<% end %>

app/views/cart/_more_info.html.erb
<div class="more-info" colspan="42">
  <p class="service"><%= leg.service_name.dehtml %></p>

  <p><span class=""><%= leg.total_passengers %></span> total passenger(s)</p>

  <% current_network.non_fixed_service_extras(leg.home_site_id).each do |extra| %>
    <% next unless leg.send(extra['FieldName']).try(:>, 0) %>
    <p><span class=""><%= leg.send(extra['FieldName']) %></span> <%= extra['Label'].dehtml %></p>
  <% end %>

  <% current_network.fixed_service_extras(leg.home_site_id).each do |extra| %>
    <% next unless leg.send(extra['FieldName']).try(:>, 0) %>
    <p><%= extra['Label'].dehtml %></p>
  <% end %>
</div>

app/views/cart/_payment.html.erb
<label><%= payment_header %></label>
<div class="hudson-subsection well">
  <%= render partial: 'payment_types' %>

  <% if offer_cc? || cc_required? %>
    <%= render partial: 'credit_card',
            locals: {f: f, required: cc_required?} %>
  <% end %>
</div>

app/views/cart/_trip.html.erb
<table class="cart">
  <% trip.legs.each.with_index do |leg, i| %>
    <tr class="base-info <%= 'first-leg' if trip.legs.first == leg %> <%= 'last-leg' if trip.legs.last == leg %>">

      <%= content_tag :td, leg.WResID, class: "wresid" if leg.WResID.present? %>

      <td class="pickup location">
        <% if trip.is_attraction? %>
          <span class="loc-name"><%= leg.DropOffLocation %></span>
        <% else %>
          <span class="loc-name"><%= leg.PickupLocation %></span>
        <% end %>
        <span class="date"><%= leg.PickupTOD.to_s(:verbosedate) %></span>
        <% if show_time_in_cart?(trip) %>
          <span class="time"><%= nice_time_display(leg.PickupTOD) %></span>
        <% end %>

        <% if trip.is_attraction? && leg.YardDepartureTOD %>
          <div class="yard-departure">
            <%= cart_attraction_pickup_time %>
            <span class="date">
              <%= nice_time_display(leg.YardDepartureTOD) %>
            </span>
          </div>
        <% end %>

        <%= render partial: 'more_info', locals: {leg: leg} %>
      </td>

      <td class="arrow">
        <% unless trip.is_attraction? %>
          <i class='fa fa-arrow-right'></i>
        <% end %>
      </td>

      <td class="dropoff location">
        <% unless trip.is_attraction? %>
          <span class="loc-name"><%= leg.DropOffLocation %></span>
          <span><%= leg.DropOffTOD.to_s(:verbosedate) %></span>
          <span><%= nice_time_display(leg.DropOffTOD) %></span>
        <% end %>

        <%= render partial: 'more_info', locals: {leg: leg} %>
      </td>

      <td class="fare-container">
        <p class="fare"><%= number_to_currency(leg.fare_without_discount) %></p>
      </td>
    </tr>

    <% if trip.booking_error %>
      <tr class="booking-error">
        <td colspan="42"><%= trip.booking_error %></td>
      </tr>
    <% end %>

    <% if leg == trip.legs.last && !read_only %>
      <tr class="actions">
        <td colspan="42" >
          <%= link_to "<i>x</i>".html_safe + cart_delete_label, delete_trip_url(trip: trip_counter),
                  class: 'delete btn btn-link', method: :post,
                  data: {confirm: cart_delete_confirm} %>

          <% if !read_only && show_flight_city_marketing?(leg) %>
            <%= link_to "<i>&#8250;</i>".html_safe + cart_flight_city_caption(leg),
                  new_trip_url(trip_index: trip_counter, leg_index: i),
                  class: 'btn btn-link' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/cart/index.html.erb
<%= content_tag(:h1, cart_h1) if cart_h1.present? %>
<%= content_tag(:div, cart_header, class: 'cart-head') if cart_header.present? %>

<%= notice_box %>

<%= render partial: 'cart', object: cart %>

<% unless cart.empty? %>
  <div class="buttons">
      <%= link_to cart_empty_label, empty_cart_url,
              class: 'empty btn btn-link', method: :post,
              data: {confirm: cart_empty_confirm} %> |
      <%= add_res_link %>

    <%= link_to checkout_label, checkout_url,
            class: 'btn hudson-button pull-right checkout-button',
            id: 'checkout-btn',
            data: {'loading-text' => 'Loading...'} %>
  </div>
<% end %>

<% if attractions_available? && !hide_attraction_attract? -%>
  <%= render partial: 'attraction_attract', locals: {attractions: attractions} %>
<% end -%>

app/views/cart/receipt.html.erb
<%= render partial: 'analytics', locals: {cart: @receipt_cart} %>

<%= content_tag(:h1, receipt_h1) if receipt_h1.present? %>
<%= content_tag(:div, receipt_header, class: 'receipt-head') if receipt_header.present? %>

<%= render partial: 'cart', object: @receipt_cart, locals: {read_only: true} %>

<%= render partial: 'preferred_rider' %>
<%= render partial: 'tripit', locals: {cart: @receipt_cart} %>


<div class="buttons">
  <%= link_to print_label, 'javascript:window.print();' %>

  <% if current_user_profile.present? %>
    | <%= link_to receipt_logout_label, logout_profiles_url,
          data: {confirm: "You will be logged out and your session will be cleared.\n\nAre you sure?"},
          class: 'logout' %>
  <% end %>

  <% if show_book_another_link? %>
    | <%= link_to book_another_label, root_url %>
  <% end %>
</div>