config/routes.rb
Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    mount HudsonBase::Engine, :at  => 'hudson_base', :as => 'hudson_base'

    # Testing
    get ':site_id/iframe_test' => 'reservations#iframe_test'

    # Configuration (old URL format)
    get 'configuration', to: redirect { |params, request|
        site_id = request.query_parameters['network_site_id'] ||
            request.session[:site_id]

        request.protocol + request.host_with_port +
        request.fullpath.sub(/\/configuration.*/, '') + '/' +
            site_id + '/configuration' },
        as: 'configuration'

    # Res - first page
    get ':site_id', to: redirect { |params, request|
        request.protocol + request.host_with_port + request.fullpath + "/res/one_way" }, as: 'root'
    get ':site_id/res/one_way' => 'reservations#one_way', as: 'oneway'
    get ':site_id/res/round_trip' => 'reservations#round_trip', as: 'roundtrip'
    get ':site_id/res/multi_leg' => 'reservations#multi_leg', as: 'multi'
    get ':site_id/res/cruise_redirect' => 'reservations#cruise'
    post ':site_id/res/update_legs' => 'reservations#update_legs', as: 'update_legs'
    get ':site_id/res/initial_locations' => 'reservations#initial_locations',
        as: 'initial_locations'
    get ':site_id/res/locations' => 'reservations#locations', as: 'locations'
    get ':site_id/res/svc_extras' => 'reservations#svc_extras', as: 'svc_extras'
    get ':site_id/res/preload' => 'reservations#preload_data', as: 'preload'

    # Res - Cruise first page
    get ':site_id/res/cruise' => 'cruise_reservations#index', as: 'cruise'
    get ':site_id/res/cruise/arriving_locations' =>
          'cruise_reservations#arriving_locations',
        as: 'cruise_arriving_locations'
    get ':site_id/res/cruise/arriving_hot_dest' =>
          'cruise_reservations#arriving_hotel_destinations',
        as: 'cruise_arr_hotel_dests'
    get ':site_id/res/cruise/arriving_hot_hotels' =>
          'cruise_reservations#arriving_hotel_hotels',
        as: 'cruise_arr_hotel_hotels'
    get ':site_id/res/cruise/booking_container' =>
          'cruise_reservations#booking_container',
        as: 'cruise_booking_container'
    get ':site_id/res/cruise/departing_locations' =>
          'cruise_reservations#departing_locations',
        as: 'cruise_dep_locations'
    get ':site_id/res/cruise/departing_hot_dest' =>
          'cruise_reservations#departing_hotel_destinations',
        as: 'cruise_dep_hotel_dests'
    post ':site_id/res/cruise/update_legs' =>
          'cruise_reservations#update_legs',
        as: 'update_cruise_legs'

    # Res - services
    get ':site_id/services/flight_cities' => 'services#flight_cities',
            as: 'flight_cities'
    get ':site_id/services' => 'services#index', as: 'services'
    post ':site_id/services/update' => 'services#update', as: 'services_update'

    # Res - cart
    get ':site_id/cart' => 'cart#index', as: 'cart'
    get ':site_id/cart/new_trip' => 'cart#new_trip', as: 'new_trip'
    post ':site_id/cart/delete' => 'cart#delete', as: 'delete_trip'
    post ':site_id/cart/empty' => 'cart#empty', as: 'empty_cart'
    post ':site_id/cart/apply_coupon' => 'cart#apply_coupon', as: 'apply_coupon'
    post ':site_id/cart/remove_coupon' => 'cart#remove_coupon',
         as: 'remove_coupon'

    # Res - checkout
    get ':site_id/checkout' => 'cart#checkout', as: 'checkout'
    post ':site_id/checkout/validate' =>
        'cart#validate_checkout', as: 'validate_checkout'
    get ':site_id/checkout/book' => 'cart#book', as: 'book'
    get ':site_id/receipt' => 'cart#receipt', :as => :receipt

    # Attractions
    get ':site_id/attractions' => 'attractions#index'
    post ':site_id/attractions' => 'attractions#index'
    match ':site_id/attractions/widget' => 'attractions#widget',
          as: 'attractions_widget', via: :all
    get ':site_id/attractions/update_info' => 'attractions#update_info',
        as: 'attraction_update_info'
    post ':site_id/attractions/validate' => 'attractions#validate',
         as: 'attraction_validate'
    get ':site_id/attractions/widget_test' => 'attractions#test_iframe'
    get ':site_id/attractions' => 'attractions#index', as: 'attractions'
    get ':site_id/attractions/details' => 'attractions#details',
        as: 'attraction_details'

    # Profiles
    match ':site_id/group' => 'profile#group_login', as: :group, via: :all
    match ':site_id/profile/group_login_window' => 'profile#group_login_window',
            as: :group_login_window, via: :all
    match ':site_id/profile/login_window' => 'profile#login_window',
            as: :login_window, via: :all
    match ':site_id/profile/login_modal' => 'profile#login_modal',
            as: :login_modal, via: :all
    get ':site_id/join_preferred_rider' => 'profile#join', as: :join_preferred_rider
    get ':site_id/reload_profile' => 'profile#reload_profile', as: :reload_profile
    get ':site_id/preferred_rider_home' => 'profile#home', as: :preferred_rider_home
    get ':site_id/profile/pr_redirect' => 'profile#pr_redirect', as: :pr_redirect
    get ':site_id/logout' => 'profile#logout', as: :logout_profiles
    get ':site_id/logout_group' => 'profile#logout_group', as: :logout_group_profile

    # Misc.
    match ':site_id/join_mailing_list_window' => 'info#join_mailing_list_window',
            as: :join_mailing_list_window, via: :all
    match ':site_id/note' => 'contact_us#process_form', as: :notes, via: :all
    get ':site_id/error' => 'info#error', as: :error_page
    get ':site_id/block_check' => 'info#block_check', as: :block_check
    get ':site_id/cookies_test' => 'application#cookies_test', as: :cookies_test

    # Configuration
    get ':site_id/configuration' => 'configuration#index',
      as: 'config_home'
    match ':site_id/config/add_site' => 'configuration#add_site', as: 'add_site', via: :all
    match 'config/advanced' => 'configuration#advanced', via: :all
    match 'config/basic' => 'configuration#basic', via: :all
    get ':site_id/config/logout_user' => 'configuration#logout_user',
      as: 'config_logout'
    post 'config/update_site_details' => 'configuration#update_site_details', as: 'update_site_details'
    match ':site/:controller/:action', via: :all
    match 'config/delete_site' => 'configuration#delete_site', via: :all
    get 'config/activate_site' => 'configuration#activate_site'
    get 'config/disable_site' => 'configuration#disable_site'
    post 'config/add_airport' => 'configuration#add_airport', as: 'add_airport'
    post 'config/delete_airport' => 'configuration#delete_airport',
         as: 'delete_airport'

# Old below - can probably be deleted
    post 'profile/login' => 'profile#login'
    match ':site_id/login' => 'hudson_base/login#index', as: :login, via: :all
    match 'groups' => 'profile#groups', :as => :groups, via: :all

    match 'update_price' => 'attractions#update_price', as: :update_price, via: :all
    match 'logout' => 'configuration#logout', :as => :logout, via: :all
    match '/' => 'reservations#index', via: :all
  end
end

app/helpers/reservations_helper.rb
require 'ostruct'

module ReservationsHelper
  def leg(index, leg)
    if leg.airport.present?
      airport = NetworkAirport.find(current_site_id, leg.airport)
    end
    airports = NetworkAirport.all(current_site_id, current_group_profile)
    airport = airports.first if airports.length == 1

    if airport && leg.PrimarySite.present?
      region = airport.service_areas.find do |sa|
        sa.provider_site_id == leg.PrimarySite
      end
    elsif airport && airport.service_areas.length == 1
      region = airport.service_areas.first
    end

    react_component 'Leg',
                    direction: leg.Direction,
                    region: region,
                    index: index,
                    airport: {
                      current: airport,
                      field_type: airport_autocomplete_field_type,
                      label: airport_labels(index, leg.Direction) +
                             field_error_label(leg, :airport),
                      airports: airports,
                      placeholder: airport_placeholder,
                      tabindex: 0 #airport_trip_index_indicator(index)
                    },
                    location: {
                      current: leg.location,
                      label: location_labels(index, leg.Direction) +
                             field_error_label(leg, :location_key),
                      placeholder: loc_placeholder
                    },
                    urls: {
                      initial_locations: initial_locations_path,
                      location_search: locations_path,
                      roundtrip: roundtrip_path
                    }
  end

  def airport_autocomplete_field_type
    config = airport_autocomplete_type(no_span: true)
    config.to_i == 0 ? :search : :list
  end

  def airport_labels(leg_index, current_direction)
    labels = { 'D' => airport_label_d, 'A' => airport_label_a }
    directional_elements(leg_index, :label, labels, current_direction)
  end

  def bag_count_label(site_id)
    site_token(site_id, 'BAGCOUNTDESC')
  end

  # Provides inline styles for the direction button if the current
  # theme colors necessitate it.
  def direction_contrast_border
    if current_theme.button_background_color == current_theme.subsection_background_color
      return "style='border: 1px solid #{current_theme.subsection_color}'".html_safe
    end
  end

  def direction_label_with_icons(dir_type)
    dir = current_trip.direction_types.find {|dt| dt.type == dir_type}

    header = content_tag :div, class: 'direction-type-diagram pull-left hudson-subsection ' do
        direction_type_icon(dir, fixed_width: true)
    end.html_safe
    pickup_phrase = ("from " + dir.pickup_label).html_safe
    dropoff_phrase = ("to " + dir.dropoff_label).html_safe
    description = content_tag :div, class: 'direction-type-desc' do
      (dir.arrival? ?
          "#{pickup_phrase}<br/>#{dropoff_phrase}" :
          "#{dropoff_phrase}<br/>#{pickup_phrase}").html_safe
    end.html_safe

    "#{header}#{description}".html_safe
  end

  # Options:
  #   except - An array of direction types to not include.
  def direction_types(options = {})
    types = current_trip.direction_types
    if options[:except]
      types.delete_if do |dir|
        dir.type[0].in?(options[:except]) || dir.type[2].in?(options[:except])
      end
    end
    types
  end

  def error_class(leg, attribute)
    'has-error' if leg.errors[attribute].any?
  end

  def field_error_label(leg, attribute)
    if leg.errors[attribute].any?
      content_tag :label, leg.errors[attribute].join('<br/>').html_safe, class: 'error-label'
    end
  end

  # Produce two labels, one for ports and the other for airports.
  def flight_date_labels(leg_index, leg)
    current_type = 'A'

    labels = {
        'A' => flight_date_label_a,
        'CA' => flight_date_label_c_a,
        'CD' => flight_date_label_c_d }
    %w(A CA CD).collect do |type|
      content_tag('label', labels[type].html_safe,
          data: {leg: leg_index, type: type}, class: 'flight-date-label',
          style: "display: " + (current_type == type ? 'block' : 'none'))
    end.join.html_safe
  end

  # Produce two labels, one for ports and the other for airports.
  def flight_time_labels(leg_index, leg)
    current_type = 'A'

    labels = {
        'A' => flight_time_label_a,
        'CA' => flight_time_label_c_a,
        'CD' => flight_time_label_c_d }
    %w(A CA CD).collect do |type|
      content_tag('label', labels[type].html_safe,
          data: {leg: leg_index, type: type},
          style: "display: " + (current_type == type ? 'block' : 'none'))
    end.join.html_safe
  end

  def direction_trip_index_indicator(leg_index)
    if leg_index == 0
      tabindex = 4
    else
      tabindex = 12
    end
    tabindex
  end

  def airport_trip_index_indicator(leg_index)
    if leg_index == 0
      tabindex = 5
    else
      tabindex = 13
    end
    tabindex
  end

  def region_trip_index_indicator(leg_index)
    if leg_index == 0
      tabindex = 6
    else
      tabindex = 14
    end
    tabindex
  end

  def location_trip_index_indicator(leg_index)
    if leg_index == 0
      tabindex = 7
    else
      tabindex = 15
    end
    tabindex
  end

  def flightTOD_trip_index_indicator(leg_index)
    if leg_index == 0
      tabindex = 8
    else
      tabindex = 16
    end
    tabindex
  end

  def trip_time_index_indicator(index)
    if index == 0
      tabindex = 9
    else
      tabindex = 17
    end
    tabindex
  end

  def flight_type_trip_index_indicator(rt_leg,leg_index)
    if !rt_leg.present? && leg_index == 0
      tabindex = 10
    else
      tabindex = 18
    end
    tabindex
  end

  def group_profile_logo
    if current_group_profile.Logo.present?
      current_group_profile.Logo
        .fix_image_urls(current_site_id)
        .gsub(/<img /, '<img class="img-responsive" ')
        .html_safe
     end
  end

  def home_header
    content_tag(:h1, home_h1) + content_tag(:h2, home_h2)
  end

  def icon_cruise
    fa_icon 'anchor'
  end

  def icon_oneway
    fa_icon 'long-arrow-right'
  end

  def icon_multi
    fa_icon 'list'
  end

  def icon_roundtrip
    fa_icon 'exchange'
  end

  def leg_container_class(leg, hide_leg = false)
    className = 'leg-container'
    className << ' hide' if hide_leg
    className
  end

  def leg_headers(leg_index, current_direction, trip_type)
    return if trip_type == :roundtrip

    labels = {}
    %w(D A).each do |dir|
      label = send("leg_header_#{trip_type}_#{dir.downcase}")
      label = (leg_index+1).ordinalize + ' ' + label if trip_type == :multi
      labels[dir] = label
    end
    directional_elements(leg_index, :h3, labels, current_direction)
  end

  def location_labels(leg_index, current_direction)
    labels = { 'D' => loc_label_d, 'A' => loc_label_a }
    directional_elements(leg_index, :label, labels, current_direction)
  end

  def profile_welcome_message(profile)
    message = profile.WEBLogonStr.blank? ? default_profile_message :
        profile.WEBLogonStr
    message.fix_image_urls(current_site_id).html_safe
  end

  def reservation_page(type, data = {}, &block)
    content_tag :div, class: "page",
        data: data.merge({page: 'reservations', type: type}) do
      login_form = render(partial: 'reservations/login_modal')
      login_form + home_header + notice_box + capture(&block)
    end
  end

  def service_extra_label(f, extra)
    popover_content = extract_popup_text(extra.label)
    if popover_content
      data_hash = {
          content: popover_content,
          toggle: 'popover', placement: 'auto bottom',
          container: 'body', trigger: 'hover click',
          html: true }
    end

    f.label extra.field_name,
        label_without_popup_text(extra.label)
          .fix_image_urls(f.object.home_site_id).html_safe,
        data: data_hash
  end

  def date_selector(leg, index, field = :FlightTOD)
    # Where should the date come from?
    if [:FlightTOD, :PickupTOD].include?(field.to_sym) &&
       leg.send("incomplete_#{field}_date").present?
      date = leg.send("incomplete_#{field}_date")
    elsif leg.send(field).present?
      date = leg.send(field)
    end

    error_classname = error_class(leg, "#{field}_date")
    field_options = {
      data: { 'date-format' => custom_date_format.blank? ? "mm/dd/yyyy" : custom_date_format.downcase},
      # readonly: true,
      class: "input-small form-control datepicker #{error_classname}"
    }
    value = date_format(date) if date

    text_field_tag "trip[#{index}][#{field}]", value, field_options
  end

  def time_selector(leg, index, field = :FlightTOD)
    # Where should the time come from?
    if [:FlightTOD, :PickupTOD].include?(field.to_sym) &&
       leg.send("incomplete_#{field}_time").present?
      time = leg.send("incomplete_#{field}_time")
    elsif leg.send(field).present?
      time = leg.send(field)
    end

    field_options = {
      ampm:   time_format == :"12_hour" ? true : false,
      minute_step: 5,
      ignore_date: true
    }
    field_options[:include_blank] = time.blank?
    field_options[:default] = { hour: time.hour, minute: time.min } if time

    error_classname = error_class(leg, "#{field}_time")
    time_select("trip[#{index}]",
                field,
                field_options,
                class: "form-control time #{error_classname}")
  end

  def trip_type_selector(current_trip_type)
    trip_types = []
    trip_types << :oneway if oneway_enabled?
    trip_types << :roundtrip if roundtrip_enabled?
    trip_types << :multi if multi_leg_enabled?
    trip_types << :cruise if cruise_enabled?(current_trip_type)

    if trip_types.length == 1 ||
       !Network::Config.show_trip_types_bar?(current_site_id, current_trip_type)
      return nil
    end

    selector = content_tag :ul, id: 'trip-type-selector', class: %w(nav nav-pills) do

      trip_types.collect do |type|
        is_active = (current_trip_type == type)

app/views/reservations/_actions.html.erb
<div class="actions">
  <% if current_user_profile.present? %>
    <%= link_to profile_home_label,
            "javascript:parent.goto('preferred_riders_home');", tabindex: -1 %>
  <% else %>
    <%= link_to profile_login_label, login_window_url, class: 'login',
                tabindex: -1 %>
  <% end %>

  <% if current_group_profile.present? && current_user_profile.present? %>
    |
    <%= link_to profile_and_group_logout_label({}, noreplace: true).gsub(/%GROUPALIAS%/, current_group_alias).html_safe,
          logout_profiles_url,
          data: {confirm: "You will be logged out and your session will be cleared.\n\nAre you sure?"},
          class: 'logout' %>

  <% elsif current_group_profile.present? %>
    |
    <%= link_to clear_group_label({}, noreplace: true).gsub(/%GROUPALIAS%/, current_group_alias).html_safe,
          logout_group_profile_url,
          class: 'logout' %>
  <% elsif current_user_profile.present? %>
    |
      <%= link_to profile_logout_label, logout_profiles_url,
            data: {confirm: "You will be logged out and your session will be cleared.\n\nAre you sure?"},
            class: 'logout' %>
  <% end %>

  <%= cart_link %>
</div>

app/views/reservations/_additional_fields.html.erb
<hr>
<div class="control-group">
  <div class="row">
    <div class="col-sm-5">
      <%= render partial: 'reservations/passengers',
              locals: { f: f, leg: leg, leg_index: leg_index } %>
    </div>
    <div class="col-sm-5 col-sm-offset-1">
      <%= render partial: 'reservations/service_extras',
              locals: { f: f, leg: leg, leg_index: leg_index } %>
    </div>
  </div>
</div>

app/views/reservations/_direction.html.erb
<label class="direction-label">Direction</label>
<div class="input-group" style="width: 100%;">
  <%= f.hidden_field :direction_type, value: f.object.direction_type %>

  <div class="btn-group direction-dropdown">
    <button type="button" id="dropdown-toggle-<%= leg_index %>"
        class="btn hudson-button dropdown-toggle" tabindex="-1"
        <%= direction_contrast_border %>
        data-toggle="dropdown">
        <span class="type-label">
          <%= direction_label_with_icons(leg.direction_type || current_trip.direction_types.first.type) %>
        </span>
        <span class="pull-right">
          <i class="pull-right fa fa-chevron-down"></i>
        </span>
    </button>
    <ul class="dropdown-menu"
        style="background-color: <%= current_theme.button_background_color %>" role="menu">
      <li class="direction-type-heading"
          style="background-color: <%= current_theme.button_background_color %>;
                 color: <%= current_theme.button_color %>"><%= direction_type_header_arriving %></li>

      <% direction_types.select(&:arrival?).each do |d| %>
        <li data-direction="<%= d.direction %>" data-type="<%= d.type %>"
            data-index="<%= leg_index %>">
          <%= content_tag :a, direction_label_with_icons(d.type), class: 'hudson-button' %>
        </li>
      <% end %>
      <li class="direction-type-heading"
          style="background-color: <%= current_theme.button_background_color %>;
                 color: <%= current_theme.button_color %>"><%= direction_type_header_departing %></li>

      <% direction_types.select(&:departure?).each do |d| %>
        <li data-direction="<%= d.direction %>" data-type="<%= d.type %>"
            data-index="<%= leg_index %>">
          <%= content_tag :a, direction_label_with_icons(d.type), class: 'hudson-button' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/reservations/_flight.html.erb
<% field = defined?(field) && field ? field.to_sym : :FlightTOD %>

<div id="flight-container-<%= leg_index %>">
  <% if defined?(date_label) && date_label %>
    <%= content_tag :label, date_label %>
  <% else %>
    <%= flight_date_labels(leg_index, leg) %>
  <% end %>
  <%= field_error_label(leg, "#{field}_date") %>

  <div class="flight-date row">
    <% if !defined?(show_date) || (defined?(show_date) && show_date) %>
      <div class="col-xs-5 date">
        <div class="form-group input-with-icon">
          <%= date_selector(leg, leg_index, field) %>
          <i class="fa fa-calendar pull-right"></i>
        </div>
      </div>
    <% end %>

    <div class="col-xs-6 time">
      <div class="flight-time-label">
        <% if defined?(time_label) && time_label %>
          <%= content_tag :label, time_label %>
        <% else %>
          <%= flight_time_labels(leg_index, leg) %>
        <% end %>
        <%= field_error_label(leg, "#{field}_time") %>
      </div>

      <div class="form-group form-inline">
        <%= time_selector(leg, leg_index, field) %>
      </div>
    </div>
  </div>


  <% if trip_type == :roundtrip %>
    <label class="rt-flight-date"><%= return_flight_date_label %></label>
    <%= field_error_label(rt_leg, "#{field}_date") %>

    <div class="flight-date row">
      <div class="col-xs-5 date">
        <div class="form-group input-with-icon">
          <%= date_selector(rt_leg, 1, field) %>
          <i class="fa fa-calendar pull-right"></i>
        </div>
      </div>

      <div class="col-xs-6 time">
        <div class="flight-time-label">
          <label><%= return_flight_time_label %></label>
          <%= field_error_label(rt_leg, "#{field}_time") %>
        </div>
        <%= content_tag :div,
                        field_error_label(rt_leg, "#{field}_time"),
                        class: 'flight-time-error' %>

        <div class="form-group form-inline">
          <%= time_selector(rt_leg, 1, field) %>
        </div>
      </div>
    </div>
  <% end %>

  <% if !defined?(flight_type) || (defined?(flight_type) && flight_type) %>
    <div id="flight-type-container-<%= leg_index %>">
      <%= f.label :FlightType, flight_type_label %>
      <%= field_error_label(leg, :FlightType) %>
      <div class="input-group">
        <select class="form-control <%= error_class(leg, :FlightType) %>" name="<%= f.object_name %>[FlightType]">
          <option value='' disabled <%= "selected" if f.object.FlightType.blank? %>><%= flight_type_placeholder %></option>
          <option value='D' <%= "selected" if f.object.FlightType == 'D' %>>Domestic</option>
          <option value='I' <%= "selected" if f.object.FlightType == 'I' %>>International</option>
        </select>
      </div>
    </div>
  <% end %>
</div>

app/views/reservations/_login_modal.html.erb
<div class='modal' id='login-modal'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>
      <%= form_tag nil, role: 'form', class: 'login-modal-form' do %>
        <input type="hidden" name="redirect_to"
               value="<%= request.base_url + request.path %>">
        <%= render partial: 'shared/login_form' %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/iframe_test.html.erb
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title></title>

  <style>
  body { margin: 0; }
  </style>
</head>

<body>
  Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
<iframe id="res_frame" allowtransparency="true" marginwidth="0" marginheight="0" vspace="0" hspace="0"
          width="100%" height="1100"
          style="overflow:hidden; background-color: transparent; background-image: none; border-top: 2px solid red; border-bottom: 2px solid red"
          class="" src="<%= services_path %>" frameborder="0" frame_id="res_frame" scrolling="no"
          ></iframe>

</body>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>
Long Test content<br>

</html>

app/views/reservations/multi_leg.html.erb
<%= render partial: 'profile' %>

<%= reservation_page(:multi, max_legs: current_trip.max_legs) do %>
  <%= form_for current_trip, as: :trip, url: update_legs_path,  html: { role: 'form' } do |f| %>
    <%= trip_type_selector(:multi) %>
    <%= render partial: 'actions' %>
    <%= multileg_header %>

    <%= hidden_field_tag :leg_count, current_trip.leg_count %>
    <% current_trip.max_legs.times do |i| %>
      <%= render partial: 'leg', locals: {
              f: f, leg: current_trip.base_legs[i], trip_type: :multi, leg_index: i,
              hide: (current_trip.leg_count < i+1),
              direction_types: direction_types } %>
    <% end %>

    <div class="multi-leg-buttons btn-group pull-left">
      <button class="btn btn-link remove-leg"><i class="fa fa-minus"></i> Remove this leg</button>
      <button class="btn btn-link add-leg"><i class="fa fa-plus"></i> Add another leg</button>
    </div>
    <button type="submit"
        data-loading-text="Loading..."
        class="submit btn btn-hudson pull-right">Continue</button>

  <% end %>
<% end %>

app/views/reservations/one_way.html.erb
<%= render partial: 'profile' %>
<%= reservation_page(:oneway) do %>
  <%= form_for current_trip, as: :trip, url: update_legs_path,  html: { role: 'form' } do |f| %>
    <%= trip_type_selector(:oneway) %>
    <%= render partial: 'actions' %>
    <%= oneway_header %>

    <%= render partial: 'leg', locals: {
            f: f, leg: current_trip.legs[0], trip_type: :oneway, leg_index: 0,
            direction_types: direction_types(except: %w(C)) } %>

    <button type="submit"
        data-loading-text="Loading..."
        class="submit btn btn-hudson pull-right">Continue</button>
  <% end %>
<% end %>

app/views/reservations/round_trip.html.erb
<%= render partial: 'profile' %>

<%= reservation_page(:roundtrip) do %>
  <%= form_for current_trip, as: :trip, url: update_legs_path,
          html: { role: 'form' } do |f| %>
    <%= trip_type_selector(:roundtrip) %>
    <%= render partial: 'actions' %>
    <%= roundtrip_header %>

    <%= render partial: 'leg', locals: {
            f: f, leg: current_trip.legs[0], trip_type: :roundtrip, leg_index: 0,
            rt_leg: current_trip.legs[1],
            direction_types: direction_types(except: %w(C))  } %>

    <button type="submit"
        data-loading-text="Loading..."
        class="submit btn btn-hudson pull-right">Continue</button>
  <% end %>
<% end %>